teleop_twist_joy_node:
  ros__parameters:
    axis_linear: 
      x: 1
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.4

    enable_button: 2
    enable_turbo_button: 5
